# Generated by Django 3.0 on 2019-12-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20191215_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='body',
        ),
        migrations.AddField(
            model_name='shopping',
            name='Query',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
