# Generated by Django 3.0 on 2019-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20191215_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='mail',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Query',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
