# Generated by Django 3.0 on 2019-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20191215_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
