# Generated by Django 3.0 on 2019-12-15 19:10

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_shopping_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='Query',
            field=models.CharField(help_text='Enter your Query', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='mail',
            field=models.EmailField(help_text='Enter your email id', max_length=254),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
