# Generated by Django 3.0 on 2019-12-15 22:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20191215_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='section',
            field=models.CharField(choices=[('order', 'Order'), ('refund', 'Refund'), ('delivery', 'Delivery'), ('buying', 'Buying')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopping',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
