# Generated by Django 3.0 on 2019-12-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20191215_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Employee', 'Employee'), ('Customer', 'Customer')], max_length=100)),
            ],
        ),
    ]
