# Generated by Django 3.0 on 2019-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
