# Generated by Django 3.0 on 2019-12-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_delete_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopping',
        ),
    ]
