# Generated by Django 3.0 on 2019-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_additem'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='discount',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='quantity',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
