# Generated by Django 3.0 on 2019-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_remove_additem_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='pic',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
