# Generated by Django 3.0 on 2019-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_additem_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
