# Generated by Django 3.0 on 2019-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
