# Generated by Django 3.0 on 2019-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_auto_20191225_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=20),
        ),
    ]
