# Generated by Django 3.0 on 2019-12-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_additem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='additem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
