# Generated by Django 3.0 on 2019-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_auto_20191226_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('', '')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='additem',
            name='size',
        ),
    ]
