# Generated by Django 3.0 on 2019-12-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_auto_20191226_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='size',
            new_name='sizes',
        ),
    ]
