# Generated by Django 3.0 on 2019-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20191226_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('', '')], default='', max_length=20),
        ),
    ]
