# Generated by Django 3.0 on 2019-12-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_sizes_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sizes',
        ),
    ]
