# Generated by Django 3.0 on 2019-12-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_delete_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('', '')], default='', max_length=20)),
                ('owners', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.Profile')),
            ],
        ),
    ]
