# Generated by Django 3.0 on 2019-12-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0030_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='size',
        ),
    ]
