# Generated by Django 3.0 on 2019-12-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0032_additem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='owners',
        ),
    ]
