# Generated by Django 3.0 on 2019-12-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_delivery_tot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='tot',
        ),
    ]
