# Generated by Django 3.0 on 2019-12-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0037_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adress',
        ),
    ]
