# Generated by Django 3.0 on 2019-12-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0039_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Profile'),
        ),
    ]
