# Generated by Django 3.0 on 2019-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0040_auto_20191227_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='add',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
