# Generated by Django 3.0 on 2019-12-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0041_auto_20191227_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='add',
            field=models.TextField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
