# Generated by Django 3.0 on 2020-01-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0043_auto_20191228_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='pincode',
            field=models.IntegerField(default=800020),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
