# Generated by Django 3.0 on 2020-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0044_auto_20200102_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='phone',
            field=models.IntegerField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
    ]
