# Generated by Django 3.0 on 2020-01-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0045_adress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='name',
            field=models.CharField(help_text='Product name', max_length=10),
        ),
        migrations.AlterField(
            model_name='additem',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('', 'Select size')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='additem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('', 'Select size')], default='', max_length=20),
        ),
    ]
